// Generated by CoffeeScript 2.0.3
(function() {
  //#
  // Input to the [[#Collector]]
  var Content;

  Content = class Content {};

  //#
// @property path
// @type String

//#
// @property file
// @type String

//#
// @property data
// @type String

}).call(this);
